[package]
name = "stellar-contract-utils"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-ft = { workspace = true }
stellar-pausable = { workspace = true }


contract-trait-macro.workspace = true
admin-sep.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
